### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by gregorg** [nabla-c0d3/nassl#1]
If I've to start a new project with nassl, I'll start it with python 3. Have you planned a port ?

**Comment by nabla-c0d3** [comment]
It's already compatible, I just haven't made it official yet.

**Comment by gregorg** [comment]
I got this error when installing with pip3 : 

```
$ pip3 install nassl --target=./lib                                                                                                                                     [18:02]
Collecting nassl
  Using cached nassl-0.15.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/gregory/pip-build-9w41d1zh/nassl/setup.py", line 67, in <module>
        OPENSSL_LIB_INSTALL_PATH = OPENSSL_INSTALL_PATH_DICT[CURRENT_PLATFORM]
    KeyError: None
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/gregory/pip-build-9w41d1zh/nassl/
```

**Comment by nabla-c0d3** [comment]
It's not on Pypi yet (but the Git repo should be Python3-compatible).

**Comment by nabla-c0d3** [comment]
By the way, why do you want to use nassl? I am curious as it only exists for https://github.com/nabla-c0d3/sslyze

**Comment by gregorg** [comment]
I followed those instructions, replacing "python" by "python3" and "pip" by "pip3" : 
```
git clone https://github.com/nabla-c0d3/nassl.git
cd nassl
pip3 install -r requirements.txt --target ./lib
wget http://zlib.net/zlib-1.2.11.tar.gz
tar xvfz  zlib-1.2.11.tar.gz
git clone https://github.com/PeterMosmans/openssl
python3 build_from_scratch.py
```

It failed at tests step : 
```
===BUILDING NASSL===
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'nassl._nassl' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/nassl
creating build/temp.linux-x86_64-2.7/nassl/_nassl
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl_SSL_CTX.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_SSL_CTX.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl_SSL.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_SSL.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl_X509.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_X509.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl_errors.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_errors.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl_BIO.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_BIO.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl_X509_EXTENSION.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_X509_EXTENSION.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl_X509_NAME_ENTRY.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_X509_NAME_ENTRY.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl_SSL_SESSION.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_SSL_SESSION.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/openssl_utils.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/openssl_utils.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/nassl_OCSP_RESPONSE.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_OCSP_RESPONSE.o -Wall
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python2.7 -c nassl/_nassl/python_utils.c -o build/temp.linux-x86_64-2.7/nassl/_nassl/python_utils.o -Wall
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/nassl/_nassl/nassl.o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_SSL_CTX.o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_SSL.o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_X509.o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_errors.o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_BIO.o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_X509_EXTENSION.o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_X509_NAME_ENTRY.o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_SSL_SESSION.o build/temp.linux-x86_64-2.7/nassl/_nassl/openssl_utils.o build/temp.linux-x86_64-2.7/nassl/_nassl/nassl_OCSP_RESPONSE.o build/temp.linux-x86_64-2.7/nassl/_nassl/python_utils.o /var/local/src/gregory/tmp/ssl/nassl/bin/openssl/linux64/libssl.a /var/local/src/gregory/tmp/ssl/nassl/bin/openssl/linux64/libcrypto.a /var/local/src/gregory/tmp/ssl/nassl/bin/zlib/linux64/libz.a -o /var/local/src/gregory/tmp/ssl/nassl/nassl/_nassl.so
===BUILDING NASSL Tests===
SSL_Tests (unittest.loader.ModuleImportFailure) ... ERROR
X509_Tests (unittest.loader.ModuleImportFailure) ... ERROR
X509_EXTENSION_Tests (unittest.loader.ModuleImportFailure) ... ERROR
SslClient_Tests (unittest.loader.ModuleImportFailure) ... ERROR
SSL_CTX_Tests (unittest.loader.ModuleImportFailure) ... ERROR
X509_NAME_ENTRY_Tests (unittest.loader.ModuleImportFailure) ... ERROR
X509Certificate_Tests (unittest.loader.ModuleImportFailure) ... ERROR
OCSP_RESPONSE_Tests (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: SSL_Tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: SSL_Tests
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/var/local/src/gregory/tmp/ssl/nassl/tests/SSL_Tests.py", line 7, in <module>
    from nassl.ssl_client import SslClient, OpenSslVersionEnum, OpenSslVerifyEnum
  File "/var/local/src/gregory/tmp/ssl/nassl/nassl/ssl_client.py", line 10, in <module>
    from typing import List
  File "lib/typing.py", line 117
    def __new__(cls, name, bases, namespace, *, _root=False):
                                              ^
SyntaxError: invalid syntax
....

(skipping next failures)
```

and when I try to load it by hand : 

```
$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nassl.x509_certificate import X509Certificate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/local/src/gregory/tmp/ssl/nassl/nassl/x509_certificate.py", line 8, in <module>
    from nassl._nassl import X509
ImportError: /var/local/src/gregory/tmp/ssl/nassl/nassl/_nassl.so: undefined symbol: _Py_ZeroStruct
>>> 
```


To reply toyour curiosity, I'm going to build a tool to manager thousands of certificates, I need to parse them and insert parsed infos to a database, I've benchmarked `nassl` and `OpenSSL.crypto`, and nassl is much much faster, provides more informations in a more accessible and more standard way.
So I have to ask: will you continue to maintain it ? If so, my choice is done ;)

**Comment by nabla-c0d3** [comment]
Have you looked at https://cryptography.io/en/latest/x509/reference/#x-509-certificate-object ? It looks quite nice and I might actually switch for parsing certificate in nassl,

**Comment by gregorg** [comment]
Thank you, I'll take a look !
