### ISSUE TITLE
Remove support for Python 3.8 & add support for Python 3.13

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/nassl#121]

**Comment by nabla-c0d3** [comment]
Released as part of v[5.3.0](https://github.com/nabla-c0d3/nassl/releases/tag/5.3.0)

**Comment by sergeevabc** [comment]
This update is unwanted, it stops Windows 7 users from using SSLyze. There is nothing wrong with Python 3.8. It has everything you need to make SSLyze work. For example, powerful [Sublime Text](https://www.sublimetext.com/) editor uses Python 3.8 for its vast plugin ecosystem and they are in no hurry to update it. Programs should serve people for as long as possible.

``` console
$ sslyze_v610.exe

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "sslyze\__main__.py", line 5, in <module>
  File "D:\a\sslyze\sslyze\sslyze\__init__.py", line 23, in <module>
  File "D:\a\sslyze\sslyze\sslyze\plugins\scan_commands.py", line 7, in <module>
  File "D:\a\sslyze\sslyze\sslyze\plugins\certificate_info\implementation.py", line 9, in <module>
  File "D:\a\sslyze\sslyze\sslyze\plugins\certificate_info\_cert_chain_analyzer.py", line 7, in <module>
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\cryptography\hazmat\primitives\hashes.py", line 9, in <module>
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.

$ sslyze_v600.exe

  Command line error: No targets to scan.
  Use -h for help.
```

**Comment by nabla-c0d3** [comment]
In this fantasy world where unpaid developers have unlimited time and resources to work on open-source projects, you are correct.

**Comment by sergeevabc** [comment]
Re: @nabla-c0d3 

A developer, whether he gets paid for his work or does it at the behest of his heart, tries to solve a problem that overwhelms people. If a tool stops serving people, why develop it at all? That is, what is wrong with rolling back this one commit exactly? Does SSLyze need something that is in Python 3.13 and what is not in Python 3.8?
