### ISSUE TITLE
cp: cannot stat /path/to/nassl_arm/build/lib.linux-i686-2.7/ while building on ARMv7

### ISSUE THREAD

**Issue by Moter8** [nabla-c0d3/nassl#24]
Again me with some ARMv7 bug, OpenSSL and zlib seem to compile fine now.

```
[Compiling for about 30mins]
 
===BUILDING NASSL===
[compiler warnings and stuff]
L/home/shell/git/nassl_arm/openssl-1.0.1i -L/home/shell/git/nassl_arm/zlib-1.2.8 -lssl -lz -lcrypto -o build/lib.linux-armv7l-2.7/nassl/_nassl.so
cp: cannot stat ‘/home/shell/git/nassl_arm/build/lib.linux-i686-2.7/*’: No such file or directory
Traceback (most recent call last):
  File "./buildAll_unix.py", line 83, in <module>
    main()
  File "./buildAll_unix.py", line 69, in main
    perform_build_task('NASSL', NASSL_BUILD_TASKS)
  File "/home/shell/git/nassl_arm/buildAll_config.py", line 35, in perform_build_task
    subprocess.check_call(command, shell=True, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cp -R /home/shell/git/nassl_arm/build/lib.linux-i686-2.7/* /home/shell/git/nassl_arm/test' returned non-zero exit status 1

```

**Comment by nabla-c0d3** [comment]
The error is 

    cp: cannot stat ‘/home/shell/git/nassl_arm/build/lib.linux-i686-2.7/*’: No such file or directory

The name of the folder doesn't seem to be lib.linux-i686-2.7. It is probably something like lib.linux-arm; have a look at what's in the build folder and then put the right name here: https://github.com/nabla-c0d3/nassl/blob/master/buildAll_unix.py#L27

**Comment by Moter8** [comment]
`lib.linux-armv7l-` :/

Compiling again...

**Comment by Moter8** [comment]
```
installing libssl.a
cp libcrypto.pc /home/shell/git/nassl_arm/build/openssl-linux32/lib/pkgconfig
chmod 644 /home/shell/git/nassl_arm/build/openssl-linux32/lib/pkgconfig/libcrypto.pc
cp libssl.pc /home/shell/git/nassl_arm/build/openssl-linux32/lib/pkgconfig
chmod 644 /home/shell/git/nassl_arm/build/openssl-linux32/lib/pkgconfig/libssl.pc
cp openssl.pc /home/shell/git/nassl_arm/build/openssl-linux32/lib/pkgconfig
chmod 644 /home/shell/git/nassl_arm/build/openssl-linux32/lib/pkgconfig/openssl.pc
mkdir: cannot create directory ‘/home/shell/git/nassl_arm/build/openssl-linux32/include/openssl-internal’: File exists
Traceback (most recent call last):
  File "./buildAll_unix.py", line 83, in <module>
    main()
  File "./buildAll_unix.py", line 61, in main
    perform_build_task('OPENSSL', OPENSSL_BUILD_TASKS, OPENSSL_DIR)
  File "/home/shell/git/nassl_arm/buildAll_config.py", line 35, in perform_build_task
    subprocess.check_call(command, shell=True, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mkdir /home/shell/git/nassl_arm/build/openssl-linux32/include/openssl-internal' returned non-zero exit status 1
```

That mkdir should probably use the -p flag? `no error if existing, make parent directories as needed`

**Comment by nabla-c0d3** [comment]
I will close this issue for now. Compiling nassl is not for the faint of heart (especially on a non-supported platform) but these errors should not be difficult to troubleshoot (mkdir failed, cp failed, etc.). If you succeed, feel free to open a pull request with the right build file. Thanks!
