### ISSUE TITLE
Alpine Linux: _nassl.so: setcontext: symbol not found

### ISSUE THREAD

**Issue by waja** [nabla-c0d3/nassl#30]
I'm trying to build sslyze on [Alpine Linux](). This is working fine for 1.1.5 and earlier. Since 1.2.0 it seems to build fine but fails on runtime:

```sh
/ # sslyze 
Traceback (most recent call last):
  File "/usr/bin/sslyze", line 11, in <module>
    load_entry_point('SSLyze==1.2.0', 'console_scripts', 'sslyze')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/sslyze/__main__.py", line 12, in <module>
    from sslyze.concurrent_scanner import ConcurrentScanner
  File "/usr/lib/python2.7/site-packages/sslyze/concurrent_scanner.py", line 9, in <module>
    from sslyze.plugins.plugin_base import PluginScanResult
  File "/usr/lib/python2.7/site-packages/sslyze/plugins/plugin_base.py", line 12, in <module>
    from sslyze.server_connectivity import ServerConnectivityInfo
  File "/usr/lib/python2.7/site-packages/sslyze/server_connectivity.py", line 13, in <module>
    from nassl.ssl_client import ClientCertificateRequested, OpenSslVersionEnum
  File "/usr/lib/python2.7/site-packages/nassl/ssl_client.py", line 7, in <module>
    from nassl import _nassl
ImportError: Error relocating /usr/lib/python2.7/site-packages/nassl/_nassl.so: setcontext: symbol not found
```
Looking into `requirements.txt` it seems that the minimum version for nassl bumped to `nassl>=1.0.0,<1.1.0` in sslyze 1.2.0.

**Comment by nabla-c0d3** [comment]
How did you build nassl? Which versions of OpenSSL did you use?

**Comment by waja** [comment]
I just installed sslyze via pip (which works fine for sslyze <= 1.1.5): 
```sh
# SSLYZE_CLI_VERSION 1.3.4; \
apk --no-cache update && apk --no-cache upgrade && \
 apk --no-cache add python py-pip openssl && \
 apk --no-cache add --virtual build-dependencies python-dev libffi-dev openssl-dev build-base wget && \
 pip install sslyze==$SSLYZE_CLI_VERSION && \
 apk del build-dependencies
```
OpenSSL is 1.0.2n on alpine 3.7:
```sh
/ # openssl version
OpenSSL 1.0.2n  7 Dec 2017
```

You can have a look the build log at https://travis-ci.org/Cyconet/docker-sslyze/builds/342726760#L440-L574 or the raw log at https://api.travis-ci.org/v3/job/342726761/log.txt.

**Comment by nabla-c0d3** [comment]
Alpine doesn't expose some API that OpenSSL (which is embedded in nassl/sslyze) uses by default. It can easily be fixed by changing the OpenSSL compilation settings in nassl, which I will do in a future release.
More details:
* https://github.com/rubinius/rubinius/issues/908
* https://github.com/openssl/openssl/issues/2545
