### ISSUE TITLE
test_client_certificate_requested failing

### ISSUE THREAD

**Issue by fabian-z** [nabla-c0d3/nassl#41]
During an update of the AUR package sslyze-git I ran into a test failure with nassl.
I forked nassl and did a bogus commit to trigger the Travis build, with the [same result](https://travis-ci.org/fabian-z/nassl). [Complete Travis log](https://api.travis-ci.org/jobs/130023650/log.txt?deansi=true).
Any pointers on this?

```
===BUILDING NASSL Tests===
test_new_bad (X509_Tests.X509_Tests) ... ok
test_as_pem (X509_Tests.X509_Tests_Online) ... ok
test_as_text (X509_Tests.X509_Tests_Online) ... ok
test_digest (X509_Tests.X509_Tests_Online) ... ok
test_get_extensions (X509_Tests.X509_Tests_Online) ... ok
test_get_issuer_name_entries (X509_Tests.X509_Tests_Online) ... ok
test_get_notAfter (X509_Tests.X509_Tests_Online) ... ok
test_get_notBefore (X509_Tests.X509_Tests_Online) ... ok
test_get_subject_name_entries (X509_Tests.X509_Tests_Online) ... ok
test_get_version (X509_Tests.X509_Tests_Online) ... ok
test_verify_cert_error_string (X509_Tests.X509_Tests_Online) ... ok
test_new_bad (X509_NAME_ENTRY_Tests.X509_NAME_ENTRY_Tests) ... ok
test_get_data (X509_NAME_ENTRY_Tests.X509_NAME_ENTRY_Tests_Online) ... ok
test_get_object (X509_NAME_ENTRY_Tests.X509_NAME_ENTRY_Tests_Online) ... ok
test_new_bad (X509_EXTENSION_Tests.X509_EXTENSION_Tests) ... ok
test_get_critical (X509_EXTENSION_Tests.X509_EXTENSION_Tests_Online) ... ok
test_get_data (X509_EXTENSION_Tests.X509_EXTENSION_Tests_Online) ... ok
test_get_object (X509_EXTENSION_Tests.X509_EXTENSION_Tests_Online) ... ok
test_matches_hostname_bad (X509Certificate_Tests.X509Certificate_Tests_Hostname_Validation) ... ok
test_matches_hostname_good (X509Certificate_Tests.X509Certificate_Tests_Hostname_Validation) ... ok
test_do_handshake (SslClient_Tests.SslClient_Tests_Handshake) ... ok
test_client_certificate_requested (SslClient_Tests.SslClient_Tests_Online) ... FAIL
test_get_certificate_chain_verify_result (SslClient_Tests.SslClient_Tests_Online) ... ok
test_get_ecdh_param (SslClient_Tests.SslClient_Tests_Online) ... ok
test_get_peer_cert_chain (SslClient_Tests.SslClient_Tests_Online) ... ok
test_get_peer_certificate (SslClient_Tests.SslClient_Tests_Online) ... ok
test_ignore_client_authentication_requests (SslClient_Tests.SslClient_Tests_Online) ... ok
test_read (SslClient_Tests.SslClient_Tests_Online) ... ok
test_shutdown (SslClient_Tests.SslClient_Tests_Online) ... ok
test_write (SslClient_Tests.SslClient_Tests_Online) ... ok
test_use_private_key (SslClient_Tests.SslClient_Tests_PrivateKey) ... ok
test_use_private_key_bad (SslClient_Tests.SslClient_Tests_PrivateKey) ... ok
test_do_handshake_bad (SSL_Tests.SSL_Tests) ... ok
test_do_handshake_bad_eof (SSL_Tests.SSL_Tests) ... ok
test_get_available_compression_methods_has_zlib (SSL_Tests.SSL_Tests) ... ok
test_get_cipher_bits (SSL_Tests.SSL_Tests) ... ok
test_get_cipher_list (SSL_Tests.SSL_Tests) ... ok
test_get_cipher_name (SSL_Tests.SSL_Tests) ... ok
test_get_client_CA_list_bad (SSL_Tests.SSL_Tests) ... ok
test_get_current_compression_method (SSL_Tests.SSL_Tests) ... ok
test_get_peer_certificate_bad (SSL_Tests.SSL_Tests) ... ok
test_get_secure_renegotiation_support (SSL_Tests.SSL_Tests) ... ok
test_get_session (SSL_Tests.SSL_Tests) ... ok
test_get_tlsext_status_type (SSL_Tests.SSL_Tests) ... ok
test_get_verify_result (SSL_Tests.SSL_Tests) ... ok
test_new (SSL_Tests.SSL_Tests) ... ok
test_new_bad (SSL_Tests.SSL_Tests) ... ok
test_pending (SSL_Tests.SSL_Tests) ... ok
test_read_bad (SSL_Tests.SSL_Tests) ... ok
test_renegotiate (SSL_Tests.SSL_Tests) ... ok
test_set_bio (SSL_Tests.SSL_Tests) ... ok
test_set_bio_bad (SSL_Tests.SSL_Tests) ... ok
test_set_cipher_list (SSL_Tests.SSL_Tests) ... ok
test_set_cipher_list_bad (SSL_Tests.SSL_Tests) ... ok
test_set_connect_state (SSL_Tests.SSL_Tests) ... ok
test_set_options_bad (SSL_Tests.SSL_Tests) ... ok
test_set_session_bad (SSL_Tests.SSL_Tests) ... ok
test_set_tlsext_host_name (SSL_Tests.SSL_Tests) ... ok
test_set_tlsext_host_name_bad (SSL_Tests.SSL_Tests) ... ok
test_set_tlsext_status_type (SSL_Tests.SSL_Tests) ... ok
test_set_verify (SSL_Tests.SSL_Tests) ... ok
test_set_verify_bad (SSL_Tests.SSL_Tests) ... ok
test_shutdown_bad (SSL_Tests.SSL_Tests) ... ok
test_write_bad (SSL_Tests.SSL_Tests) ... ok
test_check_private_key (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_check_private_key_bad (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_load_verify_locations (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_load_verify_locations_bad (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_new (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_new_bad (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_set_private_key_password_null_byte (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_set_verify (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_set_verify_bad (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_use_PrivateKey_file (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_use_PrivateKey_file_bad (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_use_certificate_file (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_use_certificate_file_bad (SSL_CTX_Tests.SSL_CTX_Tests) ... ok
test_new_bad (OCSP_RESPONSE_Tests.OCSP_RESPONSE_Tests) ... ok
test_as_text (OCSP_RESPONSE_Tests.OCSP_RESPONSE_Tests_Online) ... ok
test_basic_verify_bad (OCSP_RESPONSE_Tests.OCSP_RESPONSE_Tests_Online) ... ok

======================================================================
FAIL: test_client_certificate_requested (SslClient_Tests.SslClient_Tests_Online)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/sslyze-git/src/nassl/tests/SslClient_Tests.py", line 157, in test_client_certificate_requested
    ssl_client.do_handshake)
AssertionError: ClientCertificateRequested not raised

----------------------------------------------------------------------
Ran 80 tests in 6.657s

FAILED (failures=1)
Traceback (most recent call last):
  File "build_from_scratch.py", line 159, in <module>
    main()
  File "build_from_scratch.py", line 151, in main
    perform_build_task('NASSL Tests', NASSL_TEST_TASKS)
  File "build_from_scratch.py", line 32, in perform_build_task
    subprocess.check_call(command, shell=True, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/bin/python2.7 run_tests.py' returned non-zero exit status 1
```

**Comment by nabla-c0d3** [comment]
It looks like https://auth.startssl.com/ is not requesting a client certificate, resulting in the failed test case. Weird as I can see the certificate request when accessing it from a browser... I'll look into it.

**Comment by fabian-z** [comment]
Works for me again.
```test_client_certificate_requested (SslClient_Tests.SslClient_Tests_Online) ... ok```
