### ISSUE TITLE
I get ModuleNotFoundError: No module named 'nassl.cert_chain_verifier'

### ISSUE THREAD

**Issue by sskras** [nabla-c0d3/nassl#76]
#75 I tried compiling and installing `nassl` using Pythin 3.6.8. 
Now I get following error by trying to use it with older version of `sslyze`. 
But I am not sure this is Python version related:
```
$ python3 -m sslyze --version
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/admin2/sslyze/sslyze/__main__.py", line 6, in <module>
    from sslyze.cli.output_hub import OutputHub
  File "/home/admin2/sslyze/sslyze/cli/output_hub.py", line 4, in <module>
    from sslyze.cli.command_line_parser import ParsedCommandLine
  File "/home/admin2/sslyze/sslyze/cli/command_line_parser.py", line 14, in <module>
    from sslyze.plugins.scan_commands import ScanCommandType, ScanCommandsRepository
  File "/home/admin2/sslyze/sslyze/plugins/scan_commands.py", line 5, in <module>
    from sslyze.plugins.certificate_info.implementation import CertificateInfoImplementation
  File "/home/admin2/sslyze/sslyze/plugins/certificate_info/implementation.py", line 9, in <module>
    from sslyze.plugins.certificate_info._cert_chain_analyzer import (
  File "/home/admin2/sslyze/sslyze/plugins/certificate_info/_cert_chain_analyzer.py", line 14, in <module>
    from nassl.cert_chain_verifier import CertificateChainVerifier, CertificateChainVerificationFailed
ModuleNotFoundError: No module named 'nassl.cert_chain_verifier'
```
I took a look at dot-seprated module names:
```
$ grep \\..*import nassl/ssl_client.py
from nassl._nassl import WantReadError, OpenSSLError, WantX509LookupError
from nassl.ocsp_response import OcspResponse
from nassl.ephemeral_key_info import (
from nassl.cert_chain_verifier import CertificateChainVerificationFailed
```
These looks like they are all present:
```
$ grep \\..*import nassl/ssl_client.py | awk '{sub(/\./, "/", $2); print $2}' | while read LINE; do eval ls -ld $LINE"@(|.py)"; done
drwxrwxr-x 2 admin2 admin2 4096 Mar 20 01:34 nassl/_nassl
-rw-rw-r-- 1 admin2 admin2 7319 Mar 20 01:34 nassl/ocsp_response.py
-rw-rw-r-- 1 admin2 admin2 5076 Mar 20 01:34 nassl/ephemeral_key_info.py
-rw-rw-r-- 1 admin2 admin2 3020 Mar 20 01:22 nassl/cert_chain_verifier.py
```
But only the `nassl/cert_chain_verifier.py` seems to be failing.

Would you help me to understand the issue?

**Comment by sskras** [comment]
OK, so it looks like the installation of my newly built `nassl` gets downgraded during the install of my newly built older version of `sslyze`:
```
$ python3 -m pip install --user .
Processing /home/admin2/sslyze
Collecting nassl<2.3.0,>=2.2.0
  Using cached nassl-2.2.0-cp36-cp36m-manylinux1_x86_64.whl (3.1 MB)
Requirement already satisfied: cryptography==2.5 in /home/admin2/.local/lib/python3.6/site-packages (from sslyze==3.0.0.beta) (2.5)
Requirement already satisfied: tls-parser<1.3.0,>=1.2.0 in /home/admin2/.local/lib/python3.6/site-packages (from sslyze==3.0.0.beta) (1.2.2)
Requirement already satisfied: dataclasses in /home/admin2/.local/lib/python3.6/site-packages (from sslyze==3.0.0.beta) (0.8)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/admin2/.local/lib/python3.6/site-packages (from cryptography==2.5->sslyze==3.0.0.beta) (1.14.5)
Requirement already satisfied: six>=1.4.1 in /home/admin2/.local/lib/python3.6/site-packages (from cryptography==2.5->sslyze==3.0.0.beta) (1.15.0)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/admin2/.local/lib/python3.6/site-packages (from cryptography==2.5->sslyze==3.0.0.beta) (1.4.0)
Requirement already satisfied: pycparser in /home/admin2/.local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography==2.5->sslyze==3.0.0.beta) (2.20)
Building wheels for collected packages: sslyze
  Building wheel for sslyze (setup.py) ... done
  Created wheel for sslyze: filename=sslyze-3.0.0b0-py3-none-any.whl size=1066180 sha256=57dd4fef71035ee7fca8381174a9cccec3ae1df7313acb7ef9d02e93aee2636a
  Stored in directory: /tmp/pip-ephem-wheel-cache-gyb5efb6/wheels/7c/9d/df/473a3ef05ccc3271f50f0d69477239fc473620a6350ad90c10
Successfully built sslyze
Installing collected packages: nassl, sslyze
  Attempting uninstall: nassl
    Found existing installation: nassl 3.0.0
    Uninstalling nassl-3.0.0:
      Successfully uninstalled nassl-3.0.0
Successfully installed nassl-2.2.0 sslyze-3.0.0b0
```

So I am trying this now for `sslyze`:
```
--- a/setup.py
+++ b/setup.py
@@ -78,7 +78,8 @@ def get_include_files() -> List[Tuple[str, str]]:
     entry_points={"console_scripts": ["sslyze = sslyze.__main__:main"]},
     # Dependencies
     install_requires=[
-        "nassl>=2.2.0,<2.3.0",
+       #"nassl>=2.2.0,<2.3.0",
+        "nassl>=2.2.0",
         "cryptography==2.5",
         "tls-parser>=1.2.0,<1.3.0",
         "dataclasses ; python_version<'3.7'",  # To remove when we drop support for Python 3.6
```

**Comment by sskras** [comment]
This helped. 
Also this change was needed:
```
--- a/sslyze/plugins/certificate_info/_certificate_utils.py
+++ b/sslyze/plugins/certificate_info/_certificate_utils.py
@@ -1,4 +1,4 @@
-from _sha256 import sha256
+from hashlib import sha256
 from typing import List, cast

 from cryptography import x509
```

Otherwise I was getting:
```
ModuleNotFoundError: No module named '_sha256'
```
