### ISSUE TITLE
Add support for brainpool curves

### ISSUE THREAD

**Issue by dzabel** [nabla-c0d3/nassl#91]
To avoid stacktrace in sslyze check `--tlsv1_2` when using a server that supports brainpool curves, these should be added to nassl.

sample error:
```
 * Error when running --tlsv1_2:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * SSLyze version: 5.0.4
       * Server: 127.0.0.1:443 - 127.0.0.1
       * Scan command: tls_1_2_cipher_suites

       Traceback (most recent call last):
         File "/sslyze/sslyze/scanner/_mass_scanner.py", line 267, in _generate_result_for_completed_server_scan
    scan_cmd_result = plugin_implementation_cls.result_for_completed_scan_jobs(
         File "/sslyze/sslyze/plugins/openssl_cipher_suites/implementation.py", line 124, in result_for_completed_scan_jobs
    cipher_suite_result = completed_job.get_result()
         File "/sslyze/sslyze/plugins/plugin_base.py", line 61, in get_result
    raise self._exception
         File "/sslyze/sslyze/scanner/_jobs_worker_thread.py", line 50, in run
    return_value = job_to_complete.function_to_call(*job_to_complete.function_arguments)
         File "/sslyze/sslyze/plugins/openssl_cipher_suites/_test_cipher_suite.py", line 55, in connect_with_cipher_suite
    ephemeral_key = ssl_connection.ssl_client.get_ephemeral_key()
         File "/usr/local/lib/python3.9/site-packages/nassl-4.0.2-py3.9-linux-x86_64.egg/nassl/ssl_client.py", line 326, in get_ephemeral_key
    return NistEcDhKeyExchangeInfo(**dh_info)
         File "<string>", line 9, in __init__
         File "/usr/local/lib/python3.9/site-packages/nassl-4.0.2-py3.9-linux-x86_64.egg/nassl/ephemeral_key_info.py", line 123, in __post_init__
    curve_name = f"unknown-curve-with-openssl-id-{self.curve.value}"
       AttributeError: 'int' object has no attribute 'value'
```

releated issue sslyze:
https://github.com/nabla-c0d3/sslyze/issues/545

there was already an attempt to support brainpool curves:
https://github.com/nabla-c0d3/nassl/commit/49442263e14d09207348de137881b0a05799e2f9

but was reverted (no matter why):
https://github.com/nabla-c0d3/nassl/commit/a7e0fdb810072828a91ef6a96397e6e8d3f6ab39

**Comment by nabla-c0d3** [comment]
Fix released as part of v5.0.0.
